### ISSUE TITLE
Should we change the branch name from "master" to "main"?

### ISSUE THREAD

**Issue by kanjurer** [jenndryden/Canadian-Tech-Internships-Summer-2024#137]
Makes more sense since we are a public repo: https://sfconservancy.org/news/2020/jun/23/gitbranchname/

**Comment by jenndryden** [comment]
I completely agree - we should have changed this a long time ago. Let me look into how this can be changed!

**Comment by jenndryden** [comment]
Just fixed it, thanks for bringing this up 😄 Definitely important!
