### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by alecishuman** [jenndryden/Canadian-Tech-Internships-Summer-2024#159]
I think the Paypal software engineer intern link should be this:
[https://paypal.eightfold.ai/careers?pid=274895052576](url)
instead of what we have right now.

**Comment by Nisarg-18** [comment]
I think the link you mentioned is for a full time position

**Comment by kanjurer** [comment]
> I think the link you mentioned is for a full time position
Kek xD

**Comment by jenndryden** [comment]
hey @alecishuman, thanks for bringing this up. also @Nisarg-18 and @kanjurer for commenting 😊 it does look like the link is for a full time position - which is great - just not what this repo targets at the moment. I think intern positions are closed right now but if you do see an open Paypal positing please let us know! 😄
