### ISSUE TITLE
README.md format broken

### ISSUE THREAD

**Issue by Ksdsk** [jenndryden/Canadian-Tech-Internships-Summer-2024#86]
It's no longer a table! 
<img width="861" alt="Screenshot 2023-08-02 at 7 29 13 PM" src="https://github.com/jenndryden/Canadian-Tech-Internships-Summer-2024/assets/48192419/2dec1e8b-4883-4164-b31c-065353131cfa">

**Comment by jenndryden** [comment]
this is fixed now! thanks :)
