### ISSUE TITLE
Plans on adding links for Fall and Winter internships too?

### ISSUE THREAD

**Issue by kanjurer** [jenndryden/Canadian-Tech-Internships-Summer-2024#88]
It might be cool if we had sections for fall and winter internships also. I know it might be harder to maintain though, but having a small section for Fall/Winter could not hurt. Thoughts?

**Comment by ShevinuM** [comment]
I personally feel like we could have another readMe for it instead of adding to the same one as summer internships.

**Comment by itsaakashpatel** [comment]
I would suggest having a new Readme for the same. For the time being, we can add a section here. I'm searching for internships for winter 2024 and landed over here. :P

**Comment by kanjurer** [comment]
Closing this for the time being, it is better to take this over to [discussions](https://github.com/jenndryden/Canadian-Tech-Internships-Summer-2024/discussions) I presume.

**Comment by jenndryden** [comment]
@kanjurer great idea, sounds good to me!
